# Generated by Django 5.2.8 on 2025-11-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('markdown_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_issues', models.TextField(default='No issues reported.')),
            ],
        ),
    ]
